[package]
name = "rdoku-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

# Prevent this from being a workspace member
[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.rdoku]
path = ".."

[[bin]]
name = "solve_fuzz"
path = "fuzz_targets/solve_fuzz.rs"
test = false
doc = false

[[bin]]
name = "generator_fuzz"
path = "fuzz_targets/generator_fuzz.rs"
test = false
doc = false
